version: '2.4'
services:
  mariadb:
    image: mariadb:10.5.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nummus
    networks:
      - nummus_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 15s
      timeout: 15s
      retries: 5
    ports:
      - 3316:3306
    restart: on-failure
  nummus:
    build:
      context: .
    env_file:
      - dev.env
    depends_on: 
      mariadb:
        condition: service_healthy
    networks:
      - nummus_net
    ports:
      - 8080:80
      - 8443:443
    restart: on-failure

networks:
  nummus_net:
    driver: bridge
    